# The Document model contains options that are passed to the document generators, the generation status, and the
# final result document if generation was successful.
class Document < ApplicationRecord

  belongs_to :creator,   class_name: "User"

  mount_uploader :attachment, DocumentUploader

  before_save  :initialize_status
  before_destroy :destroy_uploader

  PENDING  = 'pending'
  WORKING  = 'working'
  COMPLETE = 'complete'
  FAILED   = 'failed'
  STATUS_VALUES = [ PENDING, WORKING, COMPLETE, FAILED ]

  PDF = 'PDF'
  CSV = 'CSV'
  FORMATS = [PDF, CSV]

  def initialize_status
    self.status = PENDING
  end

  def working?
    status == WORKING
  end

  def complete?
    status == COMPLETE
  end

  def failed?
    status == FAILED
  end

  # These methods must avoid triggering any update callbacks or a loop will be generated by :perform
  def working!
    update_column :status, WORKING
  end

  def complete!
    update_column :status, COMPLETE
  end

  def failed!
    update_column :status, FAILED
  end

  def destroy_uploader
    remove_attachment!
  end
end
